### ISSUE TITLE
Create Network Functionality with Mirror

### ISSUE THREAD

**Issue by tmhatton** [lucasessmann/DyadicInteractions#10]
In order to allow two players to be in the same scene from different PCs, we need to implement a Server/Client functionality and ee decided to use Mirror for this.

Thus, we need to 
- [x] install the Mirror package from the asset store
- [x] Create a Network Manager / Server
- [x] Create Player Prefabs, that possess the NetworkIdentity component from the Mirror package
- [x] Handle Synchronisation between players

**Comment by DiGyt** [comment]
Maybe one additional point:

- [ ] tie each client camera to the client's player object.

**Comment by JasminLWalter** [comment]
Discarded, networking is now implemented with Lightnet
