### ISSUE TITLE
Implement controller Action

### ISSUE THREAD

**Issue by Hendrik1993** [lucasessmann/DyadicInteractions#25]
- [ ]  activate controllers in Prefab "CameraRig"
- [ ]   write script to "activate" controllers just in the lab or that it doesnt give errors at home
- [ ]  implement functionality to klick with controllers
- [ ] implement functionality to imitate klick of controllers with keyboard

**Comment by JasminLWalter** [comment]
Steam VR Controller is implemented in scene. It has fall-back mode, if VR Headset cannot be detected. The networking und gaze sphere controll is handled depending on the Controller being in Fallback or VR mode
